### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  Find a cool image or icon of a car and add to images dir.
- [x]  Add car to HTML doc, such that car appears on the top left corner.
- [x]  Add background color and styling to the page.
- [x]  Cleanup any useless CSS.
