### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List
 
- [x] Make a function that moves the car a few pixels every 16ms.
- [x] Add a keypress event listener to car object.
- [x] In the event callback function, set a timer to call goCar() every 16ms.
