### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Clear setInterval when user presses space to stop car.
- [x] Set intervalID to null.
- [x] Check if intervalID is null before calling setTimer.
