### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/driving-game#5]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add CSS for directions.
- [x] Add event listener for keydown.
- [x] Add callback function keydown events.
- [x] Test car.
- [x] Cleanup CSS, code.
